FROM public.ecr.aws/lambda/python:3.9

COPY ./functions/submit/requirements.txt ./

RUN pip3 install -r requirements.txt

COPY ./functions/submit/submit.py ./

COPY ./functions/submit/connection.py ./

COPY ./functions/submit/models.py ./

CMD [ "submit.handler" ]