FROM public.ecr.aws/lambda/python:3.9

COPY ./functions/auth/requirements.txt ./

RUN pip3 install -r requirements.txt

COPY ./functions/auth/auth.py ./

COPY ./functions/auth/connection.py ./

COPY ./functions/auth/models.py ./

CMD [ "auth.handler" ]