FROM public.ecr.aws/lambda/python:3.9

COPY ./functions/survey/requirements.txt ./

RUN pip3 install -r requirements.txt

COPY ./functions/survey/survey.py ./

COPY ./functions/survey/connection.py ./

COPY ./functions/survey/models.py ./

CMD [ "survey.handler" ]